// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run against the direct connection (not the pooler), since
    // Supabase's pooler doesn't support the prepared statements Prisma needs.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
